# Use an official Python runtime as a parent image
FROM python:3.12

# Set environment variables for Python to run in unbuffered mode
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /StockVista/requirements.txt

# Expose port 8000 to allow communication to/from server
EXPOSE 8000

# Run Django development server on container startup
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
